/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.hudson.dynamic_proxy

import com.hudson.dynamic_proxy.compiler.compile
import com.hudson.dynamic_proxy.handler.InvocationHandler
import com.hudson.dynamic_proxy.real.ApiService
import com.hudson.dynamic_proxy.real.RealApiService
import java.io.File
import java.lang.reflect.Method
import java.net.URL
import java.net.URLClassLoader




class App {

    val greeting: String
        get() {
            return "Hello World!"
        }

}

fun main() {
    val handler = object : InvocationHandler {
        override fun invoke(method: Method, vararg args: Any?): Any? {
            if(method.name == "getBanner"){
                return listOf("hello", "world")
            }
            return null
        }
    }
    val proxyInstance = Proxy.newProxyInstance(RealApiService::class.java, handler) as ApiService


    println("代理返回结果${proxyInstance.getBanner()}")
}


